### ISSUE TITLE
Sate crashes whith extra dou-files.

### ISSUE THREAD

**Issue by MIWN** [SafirSDK/safir-sdk-core#343]
If you add additional parameter files to your dou directory, Sate will crash at startup with message that dou-file don't exist in loaded assemblies.
It is no problem to start safir_control and run the system.
Sate should skip the file and start anyway.

**Comment by DonOregano** [comment]
Hmm, I think I need some clarifications before I am able to reproduce this:

What is the additional parameter file? Is it a completely new parameter file, that is not built into any safir_generated library by dobmake? Or something else?

When you say "your dou directory", do you mean adding it to an overlay, or somewhere else?

Thanks!

**Comment by MIWN** [comment]
Yes, it's a completely new parameter file, that is not built into any safir_generated library by dobmake.
Several of these parameter files are created from a template after the system is built and read in code by reflection.

Error message from Sate:
_************** Exception Text **************
Safir.Dob.Typesystem.IllegalValueException: Couldn't find type Capabilities.ButtonMenu.Parameters.DefaultMapConfig in any of the loaded assemblies!
   at Safir.Dob.Typesystem.GeneratedAssemblies.LoadType(Int64 typeId)
   at Safir.Dob.Typesystem.GeneratedAssemblies.GetType(Int64 typeId)
   at Safir.Dob.Typesystem.ObjectFactory.CreateObject(Int64 typeId)
   at Sate.MainForm.GetType(Int64 typeId) in c:\j\workspace\Build tag\Config\Release\label\win7-32-vs2010-build\src\dose\dose_sate.ss\src\MainForm.cs:line 1935
   at Sate.ExplorerPanel.LoadClassHierarchy() in c:\j\workspace\Build tag\Config\Release\label\win7-32-vs2010-build\src\dose\dose_sate.ss\src\ExplorerPanel.cs:line 403
   at Sate.MainForm.MainForm_Load(Object sender, EventArgs e) in c:\j\workspace\Build tag\Config\Release\label\win7-32-vs2010-build\src\dose\dose_sate.ss\src\MainForm.cs:line 968
   at System.Windows.Forms.Form.OnLoad(EventArgs e)_

**Comment by DonOregano** [comment]
Right. I have reproduced the error now. I can make Sate ignore the file quite easily.

However, there is a larger issue here. Is this something that Core is meant to support? We currently have no tests that this works. And if the same thing was done with a non-parameter class I am sure all hell would break loose. Exactly what cases should be allowed, and in that case tested?

**Comment by DonOregano** [comment]
What actually makes sense is to have the limitation that it can only be classes that contain only parameters that can be added. (and they cannot inherit from anything containing anything but parameters)

And they must not be used as items in objects.

**Comment by DonOregano** [comment]
Apparently still crashes when trying to open a subscribed entity.

**Comment by DonOregano** [comment]
Another fix done. Hopefully this fixes the bug.
