### ISSUE TITLE
Unit test failure: light_nodes_smart_sync fails in Jenkins

### ISSUE THREAD

**Issue by DonOregano** [SafirSDK/safir-sdk-core#449]
Happens every now and then. For example build 227 in Jenkins.

```
2023-08-23T00:27:28.543112 : === Start: one_normal_one_light_ensure_only_valid_requests_and_no_unnecessary_notifications ===
2023-08-23T00:27:28.543151 : logdir: /home/jenkins/jenkins/workspace/safir-sdk-core_develop/tmp/safir-sdk-core_7.2.0~alpha1/obj-x86_64-linux-gnu/src/tests/light_nodes/test_output/smart_sync/one_normal_one_light_ensure_only_valid_requests_and_no_unnecessary_notifications
--- Launching node 1
2023-08-23T00:27:28.546093 : Launched safir_control as pid 486978.
2023-08-23T00:27:28.555029 : Launched dope_main as pid 486980.
2023-08-23T00:27:28.567523 : Waiting for safir_control 486978 to be ready
2023-08-23T00:27:38.619090 :  dose_main seems to be ready
2023-08-23T00:27:38.621914 : Launched safir_websocket as pid 487019.
--- Launching node 5
2023-08-23T00:27:38.627035 : Launched safir_control as pid 487021.
2023-08-23T00:27:38.633306 : Launched safir_websocket as pid 487023.
2023-08-23T00:27:38.699787 : --- Node 1 is connected to the DOB
2023-08-23T00:27:43.699969 : --- Node 5 is connected to the DOB
Node state received after 3 seconds
2023-08-23T00:27:46.665602 : --- node5 is now attached
2023-08-23T00:27:46.665682 : --- Node 1 is synced OK!
2023-08-23T00:27:46.665696 : --- Node 5 is synced OK!
2023-08-23T00:27:46.665701 : ---------- set_network_state=down for node5 -----------
Node state received after 3 seconds
2023-08-23T00:27:54.903159 : --- node5 is now detached
2023-08-23T00:27:54.903308 : --- Node 1 is synced OK!
2023-08-23T00:27:54.903324 : --- Node 5 is synced OK!
2023-08-23T00:27:54.903338 : --- stop node1 while node5 is detached
2023-08-23T00:27:54.903348 : Terminating all processes
2023-08-23T00:27:54.903359 :  Terminating safir_control with pid 486978
2023-08-23T00:27:55.004180 :    Terminate successful
2023-08-23T00:27:55.506905 : waiting for safir_websocket to die
2023-08-23T00:27:56.009643 : waiting for safir_websocket to die
2023-08-23T00:27:56.512984 : waiting for safir_websocket to die
2023-08-23T00:27:57.015782 : waiting for safir_websocket to die
2023-08-23T00:27:57.516580 : waiting for safir_websocket to die
2023-08-23T00:27:58.019284 : waiting for safir_websocket to die
2023-08-23T00:27:58.522366 : ---------- set_network_state=up for node5 -----------
Node state received after 3 seconds
2023-08-23T00:28:11.763134 : --- start node2
--- Launching node 2
2023-08-23T00:28:11.766054 : Launched safir_control as pid 487086.
2023-08-23T00:28:11.771065 : Launched dope_main as pid 487088.
2023-08-23T00:28:11.775445 : Waiting for safir_control 487086 to be ready
2023-08-23T00:28:23.437735 :  dose_main seems to be ready
2023-08-23T00:28:23.440134 : Launched safir_websocket as pid 487126.
2023-08-23T00:28:28.458251 : --- Node 2 is connected to the DOB
Node state received after 3 seconds
2023-08-23T00:28:31.470850 : --- node5 is now attached to a new system
2023-08-23T00:28:31.470965 : --- Node 2 is synced OK!
2023-08-23T00:28:31.470985 : --- Node 5 is synced OK!
2023-08-23T00:28:31.471003 : --- kill node2
2023-08-23T00:28:31.471015 : Terminating all processes
2023-08-23T00:28:31.471034 :  Terminating safir_control with pid 487086
2023-08-23T00:28:31.571825 :    Terminate successful
2023-08-23T00:28:32.074584 : waiting for safir_websocket to die
2023-08-23T00:28:32.574995 : waiting for safir_websocket to die
2023-08-23T00:28:33.077689 : waiting for safir_websocket to die
2023-08-23T00:28:33.579044 : waiting for safir_websocket to die
2023-08-23T00:28:34.081788 : waiting for safir_websocket to die
2023-08-23T00:28:34.583014 : waiting for safir_websocket to die
2023-08-23T00:28:34.583208 : --- Killed node2, wait for node5 to be detached again
Node state received after 3 seconds
2023-08-23T00:28:57.655215 : --- Extended wait for PD to finish, wait time 40 sec, node_5
2023-08-23T00:29:07.658821 : --- Extended wait for PD to finish, wait time 50 sec, node_5
2023-08-23T00:29:17.668312 : --- Extended wait for PD to finish, wait time 60 sec, node_5
2023-08-23T00:29:27.677042 : --- Extended wait for PD to finish, wait time 70 sec, node_5
2023-08-23T00:29:37.681550 : --- Extended wait for PD to finish, wait time 80 sec, node_5
2023-08-23T00:29:47.699176 : --- Extended wait for PD to finish, wait time 90 sec, node_5
2023-08-23T00:29:57.747156 : --- Extended wait for PD to finish, wait time 100 sec, node_5
2023-08-23T00:30:07.751146 : --- Extended wait for PD to finish, wait time 110 sec, node_5
2023-08-23T00:30:17.801470 : --- Extended wait for PD to finish, wait time 120 sec, node_5
2023-08-23T00:30:27.821585 : --- Extended wait for PD to finish, wait time 130 sec, node_5
2023-08-23T00:30:37.823931 : --- Extended wait for PD to finish, wait time 140 sec, node_5
2023-08-23T00:30:47.844027 : --- Extended wait for PD to finish, wait time 150 sec, node_5
2023-08-23T00:30:57.875244 : --- Extended wait for PD to finish, wait time 160 sec, node_5
2023-08-23T00:31:07.879158 : --- Extended wait for PD to finish, wait time 170 sec, node_5
2023-08-23T00:31:17.929526 : --- Extended wait for PD to finish, wait time 180 sec, node_5
2023-08-23T00:31:27.947138 : --- Extended wait for PD to finish, wait time 190 sec, node_5
2023-08-23T00:31:37.951561 : --- Extended wait for PD to finish, wait time 200 sec, node_5
2023-08-23T00:31:47.972280 : --- Extended wait for PD to finish, wait time 210 sec, node_5
2023-08-23T00:31:58.009393 : *** ERROR: Incorrect pool on node 5, safir_instance: 5
=== Node: 5, safir_instance: 5 ===
  Registrations:
    Safir.Dob.NodeInfo:2 - Registered
    Safir.Dob.NodeInfo:5 - Registered
  Entities:
    Safir.Dob.NodeInfo:2 - {"_DouType": "Safir.Dob.NodeInfo", "NodeName": "NormalTwo", "IpAddress": "127.0.0.1", "NodeType": "Server", "State": "Normal", "MemoryLevel": "Normal"}
    Safir.Dob.NodeInfo:5 - {"_DouType": "Safir.Dob.NodeInfo", "NodeName": "LightFive", "IpAddress": "127.0.0.1", "NodeType": "ClientKeepState", "State": "Detached", "MemoryLevel": "Normal"}
2023-08-23T00:31:58.009487 : --------------
  Expected registrations:
    Safir.Dob.NodeInfo:2 - Registered
    DoseTest.GlobalEntity:APP2 - Registered
    Safir.Dob.NodeInfo:5 - Registered
  Expected entities:
    Safir.Dob.NodeInfo:2 - _
    DoseTest.GlobalEntity:22 - version2
    Safir.Dob.NodeInfo:5 - _
2023-08-23T00:31:58.009561 : --- kill node5
2023-08-23T00:31:58.009603 : Terminating all processes
2023-08-23T00:31:58.009627 :  Terminating safir_control with pid 487021
2023-08-23T00:31:58.110402 :    Terminate successful
2023-08-23T00:31:58.613102 : waiting for safir_websocket to die
2023-08-23T00:31:59.115790 : waiting for safir_websocket to die
2023-08-23T00:31:59.618495 : waiting for safir_websocket to die
2023-08-23T00:32:00.121228 : waiting for safir_websocket to die
2023-08-23T00:32:00.623963 : waiting for safir_websocket to die
2023-08-23T00:32:01.126693 : waiting for safir_websocket to die
2023-08-23T00:32:01.126996 : --- kill node1
2023-08-23T00:32:01.127011 : Terminating all processes
2023-08-23T00:32:01.127025 :  Terminating safir_control with pid 486978
2023-08-23T00:32:01.127048 :    Terminate successful
ERROR:root:Got exception
Traceback (most recent call last):
  File "/home/jenkins/jenkins/workspace/safir-sdk-core_develop/tmp/safir-sdk-core_7.2.0~alpha1/src/tests/light_nodes/light_nodes_smart_sync.py", line 45, in test_case
    yield
  File "/home/jenkins/jenkins/workspace/safir-sdk-core_develop/tmp/safir-sdk-core_7.2.0~alpha1/src/tests/light_nodes/light_nodes_smart_sync.py", line 749, in lightnode_attaches_to_new_system_after_detached
    await check_pool(app5, initialRegApp2 + initialRegApp5, initialEntApp2 + initialEntApp5)
  File "/home/jenkins/jenkins/workspace/safir-sdk-core_develop/tmp/safir-sdk-core_7.2.0~alpha1/src/tests/light_nodes/light_nodes_smart_sync.py", line 172, in check_pool
    raise AssertionError("Incorrect pool")
AssertionError: Incorrect pool
2023-08-23T00:32:01.128880 : Incorrect pool
2023-08-23T00:32:01.128903 : *** Test failed: one_normal_one_light_ensure_only_valid_requests_and_no_unnecessary_notifications
2023-08-23T00:32:01.128912 : --- Finished: one_normal_one_light_ensure_only_valid_requests_and_no_unnecessary_notifications ---
2023-08-23T00:32:01.131449 : *** Failed:  one_normal_one_light_ensure_only_valid_requests_and_no_unnecessary_notifications
```

**Comment by DonOregano** [comment]
Fixed in develop by @joelottosson
